theme: hugo-theme-codex
title: Morgan Kerle
languageCode: en-us
baseURL: https://morgankerle.me
copyright: © {year}
params:
  dateFormat: Jan 2 2006
  github: https://github.com/morgan-dgk
  iconOrder:
    - Twitter
    - GitHub
  showPageTitleInTOC: no
  twitter: https://twitter.com/MorganDGK
markup:
  goldmark:
    renderer:
      unsafe: yes
  highlight:
    codeFences: no
menu:
  main:
    - identifier: about
      name: about
      title: About
      url: /
    - identifier: blog
      name: blog
      title: Blog
      url: /blog
    - identifier: projects
      name: projects
      title: Projects
      url: /projects
